version: '3.8'

services:

  modesfiltered:
    image: rhodan76/modesfiltered
    tty: true
    container_name: modesfiltered
    hostname: modesfiltered
    restart: always
#   in case you are using a containerized version of e.g. readsb, it's a good idea to make this container dependent on it.
#    depends_on:
#      - readsb
    environment:
      - MODES_HOST=192.168.2.5
      - MODES_PORT=30003
      - MODES_LOC=Friedrichsdorf, DE
      - MODES_WHITELIST=3E, 3F, AE, A3, AD, 3B, 4D, 15, 43
      - MODES_BLACKLIST=3C4,4CA,3C7,3C6,3C5,489,4B1,400,484,471,440,45A
      - MODES_CALLSIGNS=AAL, ADR, AIB, AFL, AFR, AMT, ANA, ASL, AUA, AUI, AWU, AZA, BAW, BCS, BEE, BEL, BER, BMR, BTI, CAL, CAO, CES, CFG, CHH, CHX, CLW, CLX, CMP, COA, CSA, CSN, CTN, DAL, DEO, DLH, EIN, EJU, ELO, ELY, ENT, EXS, EWG, ETH, EZY, FIN, GMI, GWI, HAL, HLX, IBK, IBS, ISR, JEA, KAL, KLM, LBT, LDA, LGL, LLP, MSC, NAX, NLY, NWA, PGT, PIA, QTR, ROT, RUS, RYR, SAS, SBI, SKS, SRN, SWR, SXS, TAP, TCX, THA, THY, TOM, TRA, TUI, UAE, UPS, VIM, VIR, VLG, VKG, WZZ, 2BB
