#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Check health of modesfiltered every minute
sleep 60

# define MAX_RESTART_INTERVAL to be the max time (secs) between restarts. This will make sure that the service
# will not restart too often in times of low traffic.
[[ -n "$MAX_RESTART_INTERVAL"]] && MAX_RESTART_INTERVAL=600
[[ ! -f "$MODESFILTERED_LOG_PATH/last_restart_time" ]] && date +%s > "$MODESFILTERED_LOG_PATH/last_restart_time"

if bash /scripts/check_modesfiltered_last_msg.sh; then
  # Service is OK, no action needed
  exit 0
else
  # Service is not OK, restart it if it was restarted more than MAX_RESTART_INTERVAL ago
  # pkill will kill the java process, and s6-svc will start it back up automatically
  if (( $(date +%s) - $(cat "$MODESFILTERED_LOG_PATH/last_restart_time") > MAX_RESTART_INTERVAL )); then
    pkill java
    date +%s > "$MODESFILTERED_LOG_PATH/last_restart_time"
  fi
fi
