#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Check health of modesfiltered every minute
sleep 60

if $(bash /scripts/check_modesfiltered_last_msg.sh); then
  echo "true"
else
  echo "false"
fi
