#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set +x

APPNAME="$(hostname)/modesfiltered"

echo "[$APPNAME][$(date)] Started as an s6 service"

PROG="modesfiltered.jar"
PROG_PATH="/home/pi/modesfiltered"
PIDFILE="/var/run/modes.pid"
LOGFILE="/var/log/modes.log"

# Host
if [[ -n "$MODES_HOST" ]]; then
    MODES_CMD+=("-host $MODES_HOST")
fi

# Port
if [[ -n "$MODES_PORT" ]]; then
    MODES_CMD+=("-port $MODES_PORT")
fi

# Location
if [[ -n "$MODES_LOC" ]]; then
    echo $MODES_LOC > $PROG_PATH/variables.txt
fi


# create new files from docker-compose configuration
# Whitelist
if [[ -n "$MODES_WHITELIST" ]]; then
    echo $MODES_WHITELIST > $PROG_PATH/whitelist.txt
# we did not find a configuration, so lets use the saved file from install
else
    echo "MODES_WHITELIST not configured, using standard values"
    rm $PROG_PATH/whitelist.txt
    cp $PROG_PATH/whitelist.install $PROG_PATH/whitelist.txt
fi

# Blacklist
if [[ -n "$MODES_BLACKLIST" ]]; then
    echo $MODES_BLACKLIST > $PROG_PATH/blacklist.txt
# we did not find a configuration, so lets use the saved file from install
else
     echo "MODES_BLACKLIST not configured, using standard values"
     rm $PROG_PATH/blacklist.txt
     cp $PROG_PATH/blacklist.install $PROG_PATH/blacklist.txt
fi

# Callsigns
if [[ -n "$MODES_CALLSIGNS" ]]; then
    echo $MODES_CALLSIGNS > $PROG_PATH/callsigns.txt
# we did not find a configuration, so lets use the saved file from install
else
     echo "MODES_CALLSIGNS not configured, using standard values"
     rm $PROG_PATH/callsigns.txt
     cp $PROG_PATH/callsigns.install $PROG_PATH/callsigns.txt
fi

#sleep 20

cd $PROG_PATH
touch $LOGFILE
#java -jar "${PROG}" "${MODES_CMD[@]}" > $LOGFILE 2>$LOGFILE &
echo ${PROG} ${MODES_CMD[@]}
java -jar ${PROG} ${MODES_CMD[@]} \
2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[modesfiltered] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

echo "$PROG started"
touch $PIDFILE
