#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set +x

APPNAME="$(hostname)/modesfiltered"
PROG="modesfiltered.jar"

# Host
if [[ -n "$MODES_HOST" ]]; then
    MODES_CMD+=("-host $MODES_HOST")
fi

# Port
if [[ -n "$MODES_PORT" ]]; then
    MODES_CMD+=("-port $MODES_PORT")
fi

cd "$MODESFILTERED_PROG_PATH"
java -jar ${PROG} ${MODES_CMD[@]}
#  \
# 2>&1 | stdbuf -o0 sed --unbuffered '/^$/d' | stdbuf -o0 awk '{print "[modesfiltered] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'

sleep 5