#!/usr/bin/with-contenv bash
#shellcheck shell=bash

tail -qF "${MODESFILTERED_LOG_PATH}/current" 2> /dev/null | stdbuf -o0 awk '{print "[modesfiltered] " $0}'

# Note, to reduce container log spam, you could add some `grep -v <term>` to this pipeline to reject certain lines.

sleep 1
