#!/usr/bin/with-contenv bash
#shellcheck shell=bash

if [[ -n "$VERBOSE" ]]; then
    stdbuf -oL tail -qF "${MODESFILTERED_LOG_PATH}/current" 2> /dev/null
else
    stdbuf -oL tail -qF "${MODESFILTERED_LOG_PATH}/current" 2> /dev/null | grep --line-buffered -v '] MSG, '
fi
sleep 1
