#!/usr/bin/with-contenv bash
#shellcheck shell=bash

set o=pipefail

APPNAME="$(hostname)/modesfiltered"
PROG="modesfiltered.jar"

# Host
if [[ -n "$MODES_HOST" ]]; then
    MODES_CMD+=("-host $MODES_HOST")
fi

# Port
if [[ -n "$MODES_PORT" ]]; then
    MODES_CMD+=("-port $MODES_PORT")
fi

cd "$MODESFILTERED_PROG_PATH"
java -jar ${PROG} ${MODES_CMD[@]} 2>&1 | s6-log -bp 1 n5 s400000 S10000000 "$MODESFILTERED_LOG_PATH" > /dev/null

# If the java proces dies immediately, the following sleep prevents it from "hammering"
sleep 5