#!/usr/bin/with-contenv bash
#shellcheck shell=bash

mkdir -p "$MODESFILTERED_LOG_PATH" > /dev/null 2>&1
chown nobody "$MODESFILTERED_LOG_PATH" > /dev/null 2>&1
date +%s > "$MODESFILTERED_LOG_PATH/last_restart_time"
